# Form implementation generated from reading ui file 'ui\create_new_project.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(680, 363)
        self.groupBox = QtWidgets.QGroupBox(parent=Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 40, 661, 281))
        self.groupBox.setObjectName("groupBox")
        self.projects_listView = QtWidgets.QListView(parent=self.groupBox)
        self.projects_listView.setGeometry(QtCore.QRect(10, 20, 641, 251))
        self.projects_listView.setObjectName("projects_listView")
        self.next_pushButton = QtWidgets.QPushButton(parent=Form)
        self.next_pushButton.setGeometry(QtCore.QRect(590, 330, 75, 23))
        self.next_pushButton.setObjectName("next_pushButton")
        self.remove_pushButton = QtWidgets.QPushButton(parent=Form)
        self.remove_pushButton.setGeometry(QtCore.QRect(510, 330, 75, 23))
        self.remove_pushButton.setObjectName("remove_pushButton")
        self.project_name_lineEdit = QtWidgets.QLineEdit(parent=Form)
        self.project_name_lineEdit.setGeometry(QtCore.QRect(102, 10, 561, 20))
        self.project_name_lineEdit.setObjectName("project_name_lineEdit")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(20, 10, 81, 16))
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Create new project"))
        self.groupBox.setTitle(_translate("Form", "Recent projects"))
        self.next_pushButton.setText(_translate("Form", "Next"))
        self.remove_pushButton.setText(_translate("Form", "Remove"))
        self.label.setText(_translate("Form", "Project name : "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
